services:
# Postgres database
  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/
    ports: 
      - "5432:5432"
  # kafka:
  #   image: 'bitnami/kafka:latest'
  #   volumes:
  #     - kafka_data:/app/myapp
  #   ports:
  #     - '9092:9092'
  #   environment:
  #     - KAFKA_ENABLE_KRAFT=yes
  #     - KAFKA_CFG_PROCESS_ROLES=broker,controller
  #     - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
  #     - KAFKA_BROKER_ID=1
  #     - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #     - KAKFA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
  #     - KAFKA_CFG_NODE_ID=1
volumes:
  db_data:
  kafka_data: